### ISSUE TITLE
Creator V2.2.1 run failed

### ISSUE THREAD

**Issue by xianzhiliao** [genxium/BuildingAndCraftingAndTowerDefenseGame#1]
using Creator V2.2.1 open fronted project,tip "load script [LanguageData] failed : Error: Cannot find module 'LanguageData' "

**Comment by xianzhiliao** [comment]
https://forum.cocos.org/t/i18n/42573到此链接下载i18n插件包放入工程packages目录下，i18n问题可以解决

**Comment by genxium** [comment]
最新的commit已包含所需的i18n插件 :)
